language: php
php: [ 7.1, 7.2, nightly ]

env:

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - sudo apt install graphviz
  - composer install --no-interaction --prefer-dist --optimize-autoloader
  - wget https://phar.io/releases/phive.phar
  - php phive.phar --no-progress install --trust-gpg-keys 4AA394086372C20A phpunit

script:
  - ./tools/phpunit --no-coverage

jobs:
  include:
    - stage: coverage
      php: 7.1
      script:
        - ./tools/phpunit
      after_script:
        - php phive.phar --no-progress install --trust-gpg-keys E82B2FB314E9906E php-coveralls && ./tools/php-coveralls --verbose
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: lint
      php: 7.1
      before_script:
        - wget https://phar.io/releases/phive.phar
        - php phive.phar --no-progress install --trust-gpg-keys 8E730BA25823D8B5 phpstan
      script:
        - ./tools/phpstan analyse src --level max --configuration phpstan.neon
        - composer create-project symplify/easy-coding-standard temp/ecs && temp/ecs/bin/ecs check src tests

cache:
  directories:
  - $HOME/.composer/cache/files
  - $HOME/.phive

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
